### ISSUE TITLE
Is the ability to convert wgs84 coordinate system to tm128 coordinate system also supported?

### ISSUE THREAD

**Issue by shy1008** [maRci002/proj4dart#11]
Hello, I am trying to change the general latitude and longitude wgs84 coordinate system value to the TM128 coordinate system value.

I got the desired value by converting the wgs84 coordinate system to the Tm128 coordinate system in the proj4 package provided by node js.

```
const proj4 = require('proj4');
var from = 'WGS84'
var to = 'TM128'

proj4.defs('WGS84', "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs");
proj4.defs('TM128', '+proj=tmerc +lat_0=38 +lon_0=128 +k=0.9999 +x_0=400000 +y_0=600000 +ellps=bessel +units=m +no_defs +towgs84=-115.80,474.99,674.11,1.16,-2.31,-1.63,6.43');
var xy = [126.947937,37.375219];
var result = proj4(from, to, xy); 

console.log(result) 
```

But I need a conversion function in flutter. Can you guide me?

**Comment by maRci002** [comment]
```dart
import 'package:proj4dart/proj4dart.dart';

void main() {
  final from = Projection.add(
    'WGS84',
    '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs',
  );

  final to = Projection.add(
    'TM128',
    '+proj=tmerc +lat_0=38 +lon_0=128 +k=0.9999 +x_0=400000 +y_0=600000 +ellps=bessel +units=m +no_defs +towgs84=-115.80,474.99,674.11,1.16,-2.31,-1.63,6.43',
  );

  final xy = Point(x: 126.947937, y: 37.375219);

  final result = from.transform(to, xy);
  print(result.toArray());
}
```

And if you are using `flutter_map` here is how you can configure: https://github.com/fleaflet/flutter_map/blob/master/example/lib/pages/custom_crs/Readme.md
However resulutions might be a problem so read this:
https://github.com/maRci002/proj4dart/issues/2#issuecomment-612389717

**Comment by shy1008** [comment]
thank you so much
