### ISSUE TITLE
PROJ release version

### ISSUE THREAD

**Issue by behzad-tmr** [maRci002/proj4dart#13]
According to https://proj.org/ , Could you plz declare which PROJ release version is used in this package. 
I need PROJ 7.0.0 .

**Comment by maRci002** [comment]
`Proj4dart` was ported from `Proj4js`.

> Proj4js is a JavaScript library to transform point coordinates from one coordinate system to another, including datum transformations. Originally a port of [PROJ](https://proj.org/) ([then known as PROJ.4](https://proj.org/faq.html#what-happened-to-proj-4)) and GCTCP C ([Archive](https://web.archive.org/web/20130523091752/http://edcftp.cr.usgs.gov/pub/software/gctpc/)) it is a part of the [MetaCRS](https://trac.osgeo.org/metacrs/wiki) group of projects.

_Thereby:_
The specific version of Proj.4 that is used by Proj4js is not specified, as the library is designed to work with multiple versions of Proj.4.

[Proj 6 / 7 brings grid shift transforms support](https://lists.osgeo.org/pipermail/proj/2020-October/009835.html) which is availiable in Proj4js proj4js/proj4js#363 and also availiable in Proj4dart #12.

Note: #12 added nadgrids support (`.gsb` files) but not Geodetic TIFF grids see https://github.com/maRci002/proj4dart/issues/9#issuecomment-1221261169
