### ISSUE TITLE
[question] get the epsg code from a projection

### ISSUE THREAD

**Issue by moovida** [maRci002/proj4dart#3]
Hi, I have the case in which I am reading the prj wkt from a file that is a sidecar file of a tiff file.

In the case the projection is not registered, I would like to advise the user that a certain epsg code needs to be added as definition.

Is there a way to get the epsg code from a projection object?
This would help a lot to keep a list of registered projections and handle them.

**Comment by maRci002** [comment]
Hello, basically you want to get EPSG code from `proj4 def` / `ogc wkt` / `esri wkt`.

In case of `ogc wkt` / `esri wkt` you can use @fegyi001's [wkt parser](https://pub.dev/packages/wkt_parser), warning `getAuthorityFromWKT` can return `null`.
(Alternatively you can create your own `HashMap` and add your projections by `Projection.parse`)
```
import 'package:proj4dart/proj4dart.dart';
import 'package:wkt_parser/wkt_parser.dart';

void main() {
  var wktFile =
      'PROJCS["HD72 / EOV",GEOGCS["HD72",DATUM["Hungarian_Datum_1972",SPHEROID["GRS 1967",6378160,298.247167427,AUTHORITY["EPSG","7036"]],TOWGS84[52.17,-71.82,-14.9,0,0,0,0],AUTHORITY["EPSG","6237"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4237"]],PROJECTION["Hotine_Oblique_Mercator_Azimuth_Center"],PARAMETER["latitude_of_center",47.14439372222222],PARAMETER["longitude_of_center",19.04857177777778],PARAMETER["azimuth",90],PARAMETER["rectified_grid_angle",90],PARAMETER["scale_factor",0.99993],PARAMETER["false_easting",650000],PARAMETER["false_northing",200000],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Y",EAST],AXIS["X",NORTH],AUTHORITY["EPSG","23700"]]';
  var wktObj = parseWKT(wktFile);

  var authKey = getAuthorityFromWKT(wktObj);

  if (authKey == null) {
    print('Couldn\'t extract authority');
  } else {
    print(authKey);
    var projection = Projection(authKey) ?? Projection.add(authKey, wktFile);
  }
}

String getAuthorityFromWKT(ProjWKT wkt) {
  var authority = wkt.AUTHORITY;
  if (authority == null) {
    return null;
  }

  var key = wkt.AUTHORITY.keys.toList()[0];
  return '$key:${wkt.AUTHORITY[key]}';
}
```

See similar questions on Stackoverflow [here](https://gis.stackexchange.com/questions/55196/how-can-i-get-the-proj4-string-or-epsg-code-from-a-shapefile-prj-file) or [here](https://gis.stackexchange.com/questions/7608/shapefile-prj-to-postgis-srid-lookup-table/7615), usually they use http://prj2epsg.org/search service under the hood.

**Comment by moovida** [comment]
Just to let you know that I have been finally able to complete and test this a bit and it works quite well. Thanks!
