### ISSUE TITLE
Initializing x0, y0 in stere.dart

### ISSUE THREAD

**Issue by rrrobinnn** [maRci002/proj4dart#4]
When running:
>   double lat = 0;
>   double lon = 0;
>   var pointSrc = Point(x: lon, y: lat);
>   var projSrc = Projection('EPSG:4326');
>   var projDst = Projection('Stere') ??
>       Projection.add('Stere', '+proj=stere +lat_0=90 +lon_0=0 +lat_ts=0 +ellps=WGS84 +x_0=0 y_0=0',
>       );
>   // Forward transform (lonlat -> Stereographic)
>   var pointForward = projSrc.transform(projDst, pointSrc);

I got the following error in line 107 of stere.dart (where x0 is first used):
> Unhandled exception:
> NoSuchMethodError: The method '+' was called on null.
> Receiver: null
> Tried calling: +(0.0)

Problem is solved in stere.dart by changing:
>   StereographicSouthProjection.init(ProjParams params)
>       : lat0 = params.lat0,
>         long0 = params.long0,
>         lat_ts = params.lat_ts ?? double.nan, // fix js behavior
>         x0 = params.x0,
>         y0 = params.y0,

to:
>   StereographicSouthProjection.init(ProjParams params)
>       : lat0 = params.lat0,
>         long0 = params.long0,
>         lat_ts = params.lat_ts ?? double.nan, // fix js behavior
>         x0 = params.x0 ?? 0,
>         y0 = params.y0 ?? 0,

**Comment by maRci002** [comment]
I'll take a look when I've some free time. I checked proj4js behaviour:

```js
var script = document.createElement("script");
script.onload = function() {
    proj4.defs('Stere', '+proj=stere +lat_0=90 +lon_0=0 +lat_ts=0 +ellps=WGS84 +x_0=0 y_0=0');
    console.log(proj4('EPSG:4326', 'Stere', [0,0]));
};

var scriptPath = "https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.6.2/proj4.js";
script.setAttribute("src", scriptPath);
document.head.appendChild(script);
```

Output: `[0, NaN]`

**Comment by maRci002** [comment]
Sorry for late response, I checked this issue and the problem is that your proj4 string is invalid:
`+proj=stere +lat_0=90 +lon_0=0 +lat_ts=0 +ellps=WGS84 +x_0=0 y_0=0`

the `y_0=0` part should be `+y_0=0`
So the final version: `+proj=stere +lat_0=90 +lon_0=0 +lat_ts=0 +ellps=WGS84 +x_0=0 +y_0=0`
