### ISSUE TITLE
Adding support for nadgrids

### ISSUE THREAD

**Issue by maRci002** [maRci002/proj4dart#9]
Proj4js [started to support nadgrids](https://github.com/proj4js/proj4js/pull/363) so it would be a nice feature to be implemented.

**Comment by maRci002** [comment]
This will be implemented only if someone needs it.

For example you want to change `+towgs84=...` to `+nadgrids=xxx.gsb`

**Comment by MaxiStefan** [comment]
Hey, I read about the nadgrids from (https://github.com/proj4js/proj4js/pull/363 and  the discussion in https://github.com/maRci002/proj4dart/issues/8). I have also encountered a few problems from converting from one CRS to another and I have come across a python implementation of proj that uses grid files such as .tif, .gtx and .gsb. Have you had the time to look into the dart support of these features?

**Comment by maRci002** [comment]
#12 added nadgrids support (`.gsb` files) which is based on proj4js/proj4js#363

`.tif` file type is a high quality image.
`.gtx` file type isn't supported by proj4js and so does this project, Pull requests are always welcome.
